services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 127.0.0.1:9898:9898
    # bind nginx config
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - proxy-helper
  proxy-helper:
    build: .
    command: '--proxyTarget=file:///visualizer-helper --port=3007'
    init: true
    volumes:
      - ${VISUALIZER_HELPER_VOLUME}:/visualizer-helper
    restart: unless-stopped
